[package]
name = "wasmer/wasixcc"
version = "0.2.2"
entrypoint = "wasixcc"

[dependencies]
"wasmer/clang" = "20.1.501-rc.1"

[[module]]
name = "wasixcc"
source = "target/wasm32-wasmer-wasi/release/wasixcc.wasm"

[[command]]
name = "wasixcc"
module = "wasixcc"
runner = "https://webc.org/runner/wasi"
[command.annotations.wasi]
env = ["WASIXCC_SYSROOT_PREFIX=/sysroot", "WASIXCC_LLVM_LOCATION=/"]

[[command]]
name = "wasix++"
module = "wasixcc"
runner = "https://webc.org/runner/wasi"
[command.annotations.wasi]
env = ["WASIXCC_SYSROOT_PREFIX=/sysroot", "WASIXCC_LLVM_LOCATION=/"]

[[command]]
name = "wasixcc++"
module = "wasixcc"
runner = "https://webc.org/runner/wasi"
[command.annotations.wasi]
env = ["WASIXCC_SYSROOT_PREFIX=/sysroot", "WASIXCC_LLVM_LOCATION=/"]

[[command]]
name = "wasixld"
module = "wasixcc"
runner = "https://webc.org/runner/wasi"
[command.annotations.wasi]
env = ["WASIXCC_SYSROOT_PREFIX=/sysroot", "WASIXCC_LLVM_LOCATION=/"]

[[command]]
name = "wasixar"
module = "wasixcc"
runner = "https://webc.org/runner/wasi"
[command.annotations.wasi]
env = ["WASIXCC_LLVM_LOCATION=/"]

[[command]]
name = "wasixnm"
module = "wasixcc"
runner = "https://webc.org/runner/wasi"
[command.annotations.wasi]
env = ["WASIXCC_LLVM_LOCATION=/"]

[[command]]
name = "wasixranlib"
module = "wasixcc"
runner = "https://webc.org/runner/wasi"
[command.annotations.wasi]
env = ["WASIXCC_LLVM_LOCATION=/"]
